In [1]:
################################################################
# Rolling 2 dice: sample space and events 
#
# file: prob_basics_rolling_2_dices.R
################################################################
library(tidyverse)
# create sample space
Omega <- expand.grid(x=1:6, y=1:6) %>% as_tibble()
Omega
# A = first die = 1, B = sum of the scores is 6
A <- Omega %>% filter(x==1)  
A
B <- Omega %>% filter(x+y==6)
B
# A and B
intersect(A,B)
# A or B
union(A,B)
# not A and not B
intersect(setdiff(Omega,A),setdiff(Omega,B))
setdiff(Omega,union(A,B))

-- Attaching core tidyverse packages ------------------------ tidyverse 2.0.0 --
v dplyr     1.1.4     v readr     2.1.5
v forcats   1.0.0     v stringr   1.5.1
v ggplot2   3.5.0     v tibble    3.2.1
v lubridate 1.9.3     v tidyr     1.3.1
v purrr     1.0.2
-- Conflicts ------------------------------------------ tidyverse_conflicts() --
x dplyr::filter() masks stats::filter()
x dplyr::lag()    masks stats::lag()
i Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

   x y
1  1 1
2  2 1
3  3 1
4  4 1
5  5 1
6  6 1
7  1 2
8  2 2
9  3 2
10 4 2
11 5 2
12 6 2
13 1 3
14 2 3
15 3 3
16 4 3
17 5 3
18 6 3
19 1 4
20 2 4
21 3 4
22 4 4
23 5 4
24 6 4
25 1 5
26 2 5
27 3 5
28 4 5
29 5 5
30 6 5
31 1 6
32 2 6
33 3 6
34 4 6
35 5 6
36 6 6

  x y
1 1 1
2 1 2
3 1 3
4 1 4
5 1 5
6 1 6

  x y
1 5 1
2 4 2
3 3 3
4 2 4
5 1 5

  x y
1 1 5

   x y
1  1 1
2  1 2
3  1 3
4  1 4
5  1 5
6  1 6
7  5 1
8  4 2
9  3 3
10 2 4

   x y
1  2 1
2  3 1
3  4 1
4  6 1
5  2 2
6  3 2
7  5 2
8  6 2
9  2 3
10 4 3
11 5 3
12 6 3
13 3 4
14 4 4
15 5 4
16 6 4
17 2 5
18 3 5
19 4 5
20 5 5
21 6 5
22 2 6
23 3 6
24 4 6
25 5 6
26 6 6

   x y
1  2 1
2  3 1
3  4 1
4  6 1
5  2 2
6  3 2
7  5 2
8  6 2
9  2 3
10 4 3
11 5 3
12 6 3
13 3 4
14 4 4
15 5 4
16 6 4
17 2 5
18 3 5
19 4 5
20 5 5
21 6 5
22 2 6
23 3 6
24 4 6
25 5 6
26 6 6

In [2]:
################################################################
# Urn Models
# Elementary events and their probabilities: direct 
# determination 
#
# file: prob_basics_urn_models_simple_version_without_gtools.R
################################################################
# A large number of discrete probability spaces can be traced back to
# so-called urn models. An urn contains n balls, which do not all have
# to be different. From these urns r balls are drawn with or without
# replacement. For the result of the drawing, the order or only
# the quantity of the drawn balls can be of importance. 
# Here an urn with 10 balls is considered. 5 of them are red, 3 balls
# are blue and 2 balls are green. 3 balls are drawn. The following 4
# cases should be distinguished:
# I Drawing with replacement with respect to the order
# II Drawing with replacement without observing the order
# III Drawing without replacement with respect to the order
# IV Drawing without replacement without observing the order
# a) Determine suitable event spaces and its sizes to describe the random 
# experiment. 
# b) Determine the probabilities of all elementary events in $\Omega$
# using a Laplace model, i.e. as a determination of the ratio of the
# number of favorable cases by the number of all cases. 
# Hint: To determine the probabilities with R, assume that the
# n balls are numbered consecutively, i.e. they are distinguishable,
# and that the order is first observed in a drawing. Every
# r-variation of the numbers 1 to n is equally probable. Determine
# the set of all these drawings and map each drawing to the corresponding 
# elementary event. By dividing the number of drawings belonging to an 
# elementary event and the number of all drawings, you can obtain the 
# corresponding probabilities. 

library(tidyverse)

# Bag with 10 balls: 5*red, 3*blue und 2*green 
bag <- rep(c("r","b","g"),c(5,3,2))
bag

# I: sampling r=3 balls with replacement regarding the order
sample.with.repl.ordered <- tibble(
  # construct all possible r-variations of 1,2,...,10
  x.1 = rep(1:100, each=100, length.out=10^3),
  x.2 = rep(1:10, each=10, length.out=10^3),
  x.3 = rep(1:10,length.out = 10^3)
) %>%
  # the following operations must be performed rowwise
  rowwise() %>%
  mutate(
    # maps the numbered balls to the corresponding colors
    event = c(bag[x.1],bag[x.2],bag[x.3]) %>% paste(collapse = "")
  ) %>%
  # regard only the events
  select(event) %>%
  # count the number of elementary events; all are equally like
  group_by(event) %>%
  mutate(
    prob = n()/10^3
  ) %>%
  # remove duplicates
  unique()

# II: sampling 3 balls with replacement regarding the order
sample.with.repl.unordered <- tibble(
  # construct all possible r-variations
  x.1 = rep(1:100, each=100, length.out=10^3),
  x.2 = rep(1:10, each=10, length.out=10^3),
  x.3 = rep(1:10,length.out = 10^3)
) %>%
  # the following operations must be performed rowwise
  rowwise() %>%
  mutate(
    # maps the numbered balls to the corresponding colors and consider only the
    # set of drawan colors
    event = c(bag[x.1],bag[x.2],bag[x.3]) %>% sort() %>% paste(collapse = "")
  ) %>%
  # regard only the events
  select(event) %>%
  # count the number of elementary events; all are equally like
  group_by(event) %>%
  mutate(
    prob = n()/10^3
  ) %>%
  # remove duplicates
  unique()

# III: sampling r=3 balls without replacement und regard the order
sample.without.repl <- matrix(data=0, ncol = 3, nrow = 10*9*8)
# construct all possible r-variations
l <- 1
for (i in 1:10) {
  for (j in setdiff(1:10,i)) {
    for (k in setdiff(1:10,c(i,j))) {
      sample.without.repl[l,] <- c(i,j,k)
      l <- l+1
    }
  }
} 

sample.without.repl %>%
  # convert to a tibble
  as_tibble() %>%
  # the following operations must be performed rowwise
  rowwise() %>%
  mutate(
    # maps the numbered balls to the corresponding colors
    event = c(bag[V1],bag[V2],bag[V3]) %>% paste(collapse = "")
    ) %>%
  # consider only the elementary events
  select(event) %>%
  # counts the number of elementary events (all are equally like)
  group_by(event) %>%
  mutate(
    prob = n()/(10*9*8)
  ) %>%
  unique() -> sample.without.repl.ordered

# IV: sampling 3 balls without replacement without regarding the order
sample.without.repl %>%
  # convert to a tibble
  as_tibble() %>%
  # the following operations must be performed rowwise
  rowwise() %>%
  mutate(
    # maps the numbered balls to the corresponding colors and consider only the
    # set of drawan colors
    event = c(bag[V1],bag[V2],bag[V3]) %>% sort() %>% paste(collapse = "")
  ) %>%
  # consider only the elementary events
  select(event) %>%
  # counts the number of elementary events (all are equally like)
  group_by(event) %>%
  mutate(
    prob = n()/(10*9*8)
  ) %>%
  unique() -> sample.without.repl.unorderd

 [1] "r" "r" "r" "r" "r" "b" "b" "b" "g" "g"

Warning message:
"The `x` argument of `as_tibble.matrix()` must have unique column names if
`.name_repair` is omitted as of tibble 2.0.0.
i Using compatibility `.name_repair`."

In [3]:
###############################################################################
# Consider two gamblers whose capitals sum to 7 dollar, so that as soon as one 
# has all seven dollars the other is ruined and the game stops.  Plays form 
# independent trials with even chances for winning and losing. Let X[n] be the 
# capital of the first gambler at the end of the nth play.
# a) Determine the probabilities of the values of X[3] if X[1]=3.
# b) Simulate for every possible initial value of X[1] the values of X[10].
# c) Describe the probabilities P(X[2]=j | X[1]=j) by 8x8 matrix P.
# d) Show that P^n contains the probabilities P(X[n]=j | X[1]=i).
# e) Evaluate P^10 and compare it with the relative frequencies of X[10] given 
#    by 100 simulations.
# f) Estimate the probabilites of the stop of the by evaluating P^50
#
# file: prob_gamblers_ruin.R
###############################################################################
library(tidyverse)

# a) 
# X[1]                        3 
#                 0.5|                  | 0.5
# X[2]               2                  4
#             0.5|       |0.5    0.5|      |0.5      
# X[3]           1       3          3      5
#               0.25    0.25       0.25   0.25

# c) transition matrix
P <- matrix(data = 0, ncol = 8, nrow = 8, byrow = FALSE)
P[1,1] <- 1
P[8,8] <- 1
for (i in 2:7) {
  P[i,i-1] <- 0.5
  P[i,i+1] <- 0.5
}
P

# c)  Simulation
n.sim <- 10
sim.games <- matrix(data = 0, nrow = 6, ncol = n.sim, byrow = TRUE)
sim.games[,1] <- 1:6
# store whole games
for (j in 1:6) {
  for (i in 2:n.sim) {
    sim.games[j,i] <- case_when(
      sim.games[j,i-1]==0 ~ 0,
      (sim.games[j,i-1] < 7) & (sim.games[j,i-1] > 0) ~ 
        sample(c(sim.games[j,i-1]-1,sim.games[j,i-1]+1), size = 1, replace = FALSE),
      sim.games[j,i-1]==7 ~ 7
    )
  }
}
colnames(sim.games) <- rep("value.",n.sim) %>% paste(1:n.sim, sep="")
rownames(sim.games) <- rep("init.",6) %>% paste(1:6, sep="")
sim.games

# d) P( X[10] = j | X[1]=i ) = P^n_(i,j) Chapman-Kolmogoroff equation

# e) 
P.10 <- P
for (i in 2:10) {
  P.10 <- P.10 %*% P
}
colnames(P.10) <- rep("X[10]=",8) %>% paste(0:7, sep="")
rownames(P.10) <- rep("X[1]=",8) %>% paste(0:7, sep="")
P.10 %>% round(digits=3)
# X[10]=0 X[10]=1 X[10]=2 X[10]=3 X[10]=4 X[10]=5 X[10]=6 X[10]=7
# X[1]=0   1.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000
# X[1]=1   0.754   0.041   0.000   0.087   0.000   0.064   0.000   0.054
# X[1]=2   0.549   0.000   0.128   0.000   0.151   0.000   0.064   0.107
# X[1]=3   0.344   0.087   0.000   0.192   0.000   0.151   0.000   0.226
# X[1]=4   0.226   0.000   0.151   0.000   0.192   0.000   0.087   0.344
# X[1]=5   0.107   0.064   0.000   0.151   0.000   0.128   0.000   0.549
# X[1]=6   0.054   0.000   0.064   0.000   0.087   0.000   0.041   0.754
# X[1]=7   0.000   0.000   0.000   0.000   0.000   0.000   0.000   1.000

# store X[10] in 100 simulations
final.values <- matrix(data = 0, ncol = 6, nrow = 100, byrow = TRUE)
for (k in 1:100) {
  for (j in 1:6) {
    g <- rep(0,n.sim)
    g[1] <- j
    for (i in 2:n.sim) {
      g[i] <- case_when(
        g[i-1]==0 ~ 0,
        (g[i-1] < 7) & (g[i-1] > 0) ~ 
          sample(c(g[i-1]-1,g[i-1]+1), size = 1, replace = FALSE),
        g[i-1]==7 ~ 7
      )
    }
    final.values[k,j] <- g[n.sim]
  }
}
final.values

# estimation the ratios of the final values after n.sim games
tibble(value = 0:7) %>%
  left_join(final.values %>% as_tibble() %>% count(V1) %>% 
              rename(value = V1, init.1 = n), by = "value") %>%
  left_join(final.values %>% as_tibble() %>% count(V2) %>% 
              rename(value = V2, init.2 = n), by = "value") %>%
  left_join(final.values %>% as_tibble() %>% count(V3) %>% 
              rename(value = V3, init.3 = n), by = "value") %>%
  left_join(final.values %>% as_tibble() %>% count(V4) %>% 
              rename(value = V4, init.4 = n), by = "value") %>%
  left_join(final.values %>% as_tibble() %>% count(V5) %>% 
              rename(value = V5, init.5 = n), by = "value") %>%
  left_join(final.values %>% as_tibble() %>% count(V6) %>% 
              rename(value = V6, init.6 = n), by = "value") %>%
  # exchange NA by 0 and divide by 50
  mutate(
    init.1 = replace_na(init.1, 0)/100,
    init.2 = replace_na(init.2, 0)/100,
    init.3 = replace_na(init.3, 0)/100,
    init.4 = replace_na(init.4, 0)/100,
    init.5 = replace_na(init.5, 0)/100,
    init.6 = replace_na(init.6, 0)/100) -> estimated.ratios
estimated.ratios %>% as.matrix() %>% t() -> M
M <- M[2:7,]
colnames(M) <-  rep("X[10]=",8) %>% paste(0:7, sep="")
rownames(M) <- rep("X[1]=",6) %>% paste(1:6, sep="")
M
# A tibble: 8 x 7
# value init.1 init.2 init.3 init.4 init.5 init.6
# <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>
# 1     0   0.76   0.46   0.3    0.18   0.11   0.03
# 2     1   0      0.07   0      0.12   0      0.04
# 3     2   0.1    0      0.17   0      0.08   0   
# 4     3   0      0.19   0      0.2    0      0.08
# 5     4   0.08   0      0.22   0      0.2    0   
# 6     5   0      0.14   0      0.21   0      0.07
# 7     6   0.04   0      0.1    0      0.08   0   
# 8     7   0.02   0.14   0.21   0.29   0.53   0.78

# f)
n <- 50
P.50 <- P
for (i in 2:50) {
  P.50 <- P.50 %*% P
}
colnames(P.50) <- rep("X[50]=",8) %>% paste(0:7, sep="")
rownames(P.50) <- rep("X[1]=",8) %>% paste(0:7, sep="")
# aproximation of a stop with value=0 or value=7 
P.50[2:7,c(1,8)]
#         X[50]=0   X[50]=7
# X[1]=1 0.8555890 0.1414571
# X[1]=2 0.7117630 0.2829143
# X[1]=3 0.5679370 0.4254256
# X[1]=4 0.4254256 0.5679370
# X[1]=5 0.2829143 0.7117630
# X[1]=6 0.1414571 0.8555890

# exact values
# transition probabilities from the transient states 1 to 6 to the
# absorbing states 0 and 7

# probabilities of a transition from a transient state to another transient state
Q <- P[2:7,2:7] 
# probabilities of a transition from a transient state in an absorbing state
B <- P[2:7,c(1,8)]
# B.n = (I+Q+Q^2+...+Q°(n-1))*B, B.n[i,j] is the probanility that starting from
# a transient state i (1,...,6) to enter an absorbing state j (0,7) at or before
# the n-th step
# G=(I+Q+Q^2+...)*B = (I-Q)^-1 * B, G[i,j] is the probability of ever reaching
# an absorbing state j from a transient state i

I <- matrix(data=0, nrow = 6, ncol = 6, byrow = TRUE)
for (i in 1:6) I[i,i] <- 1
# solve(I-Q) is the inverse of (I-Q)
solve(I-Q) %*% B -> G
colnames(G) <- c("value=0","value=7")
rownames(G) <- rep("start with",6) %>% paste(1:6)
G
#               value=0   value=7
# start with 1 0.8571429 0.1428571
# start with 2 0.7142857 0.2857143
# start with 3 0.5714286 0.4285714
# start with 4 0.4285714 0.5714286
# start with 5 0.2857143 0.7142857
# start with 6 0.1428571 0.8571429

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
[2,] 0.5  0.0  0.5  0.0  0.0  0.0  0.0  0.0
[3,] 0.0  0.5  0.0  0.5  0.0  0.0  0.0  0.0
[4,] 0.0  0.0  0.5  0.0  0.5  0.0  0.0  0.0
[5,] 0.0  0.0  0.0  0.5  0.0  0.5  0.0  0.0
[6,] 0.0  0.0  0.0  0.0  0.5  0.0  0.5  0.0
[7,] 0.0  0.0  0.0  0.0  0.0  0.5  0.0  0.5
[8,] 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0

       value.1 value.2 value.3 value.4 value.5 value.6 value.7 value.8 value.9
init.1 1       2       1       2       3       2       3       2       3
init.2 2       1       2       1       0       0       0       0       0
init.3 3       2       1       0       0       0       0       0       0
init.4 4       5       4       3       2       1       2       1       0
init.5 5       6       7       7       7       7       7       7       7
init.6 6       7       7       7       7       7       7       7       7
       value.10
init.1 4
init.2 0
init.3 0
init.4 0
init.5 7
init.6 7

       X[10]=0 X[10]=1 X[10]=2 X[10]=3 X[10]=4 X[10]=5 X[10]=6 X[10]=7
X[1]=0 1.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000
X[1]=1 0.754   0.041   0.000   0.087   0.000   0.064   0.000   0.054
X[1]=2 0.549   0.000   0.128   0.000   0.151   0.000   0.064   0.107
X[1]=3 0.344   0.087   0.000   0.192   0.000   0.151   0.000   0.226
X[1]=4 0.226   0.000   0.151   0.000   0.192   0.000   0.087   0.344
X[1]=5 0.107   0.064   0.000   0.151   0.000   0.128   0.000   0.549
X[1]=6 0.054   0.000   0.064   0.000   0.087   0.000   0.041   0.754
X[1]=7 0.000   0.000   0.000   0.000   0.000   0.000   0.000   1.000

      [,1] [,2] [,3] [,4] [,5] [,6]
 [1,] 0    5    0    0    7    7
 [2,] 0    5    2    0    7    3
 [3,] 0    5    7    1    7    7
 [4,] 2    3    2    5    4    7
 [5,] 0    0    4    5    2    7
 [6,] 0    0    6    3    4    5
 [7,] 2    1    0    5    0    7
 [8,] 0    7    0    0    4    7
 [9,] 4    0    0    7    7    7
[10,] 0    0    7    0    7    7
[11,] 0    3    0    3    7    7
[12,] 6    0    2    3    4    7
[13,] 4    7    6    7    7    5
[14,] 0    0    0    0    7    3
[15,] 0    7    2    7    2    7
[16,] 0    7    0    0    7    7
[17,] 2    0    4    7    7    7
[18,] 2    5    2    7    4    3
[19,] 0    1    0    3    4    7
[20,] 0    0    7    1    7    7
[21,] 0    3    2    0    7    7
[22,] 0    3    0    3    7    0
[23,] 0    0    2    5    7    7
[24,] 0    1    4    3    7    7
[25,] 0    5    0    3    4    7
[26,] 0    3    0    3    4    7
[27,] 4    0    4    7    6    5
[28,] 0    5    7    7    7    7
[29,] 0    5    0    7    7    7
[30,] 0    5    0    0    7    7
[31,] ...  ...  ...  ...  ...  ...
[32,] 0    0    2    0    7    7
[33,] 0    3    7    7    6    7
[34,] 0    0    0    7    7    3
[35,] 0    0    2    7    7    7
[36,] 0    5    7    3    6    7
[37,] 0    0    0    7    7    7
[38,] 0    1    4    5    2    7
[39,] 0    0    0    5    7    7
[40,] 0    3    2    7    0    7
[41,] 2    3    0    0    6    3
[42,] 2    0    0    0    7    7
[43,] 0    7    7    7    7    7
[44,] 2    0    0    0    6    7
[45,] 0    5    0    7    2    7
[46,] 0    7    7    5    4    7
[47,] 2    7    2    0    4    7
[48,] 0    0    7    3    0    7
[49,] 0    0    0    1    7    5
[50,] 0    7    7    3    7    7
[51,] 0    0    2    1    7    7
[52,] 4    0    2    7    7    3
[53,] 0    0    2    3    4    7
[54,] 0    7    7    0    7    7
[55,] 0    0    0    3    7    1
[56,] 0    3    7    7    7    7
[57,] 4    3    4    5    7    7
[58,] 0    0    7    1    7    3
[59,] 0    0    2    7    7    7
[60,] 0    0    4    3    7    7
[61,] 0    0    2    1    0    5

       X[10]=0 X[10]=1 X[10]=2 X[10]=3 X[10]=4 X[10]=5 X[10]=6 X[10]=7
X[1]=1 0.75    0.00    0.12    0.00    0.10    0.00    0.01    0.02
X[1]=2 0.49    0.07    0.00    0.16    0.00    0.17    0.00    0.11
X[1]=3 0.38    0.00    0.25    0.00    0.18    0.00    0.03    0.16
X[1]=4 0.21    0.11    0.00    0.21    0.00    0.13    0.00    0.34
X[1]=5 0.11    0.00    0.07    0.00    0.20    0.00    0.06    0.56
X[1]=6 0.02    0.05    0.00    0.08    0.00    0.07    0.00    0.78

       X[50]=0   X[50]=7
X[1]=1 0.8555890 0.1414571
X[1]=2 0.7117630 0.2829143
X[1]=3 0.5679370 0.4254256
X[1]=4 0.4254256 0.5679370
X[1]=5 0.2829143 0.7117630
X[1]=6 0.1414571 0.8555890

             value=0   value=7
start with 1 0.8571429 0.1428571
start with 2 0.7142857 0.2857143
start with 3 0.5714286 0.4285714
start with 4 0.4285714 0.5714286
start with 5 0.2857143 0.7142857
start with 6 0.1428571 0.8571429